### ISSUE TITLE
ES6000 RedrivePolicy error for Deadletter Queue

### ISSUE THREAD

**Issue by keironlowe-edriving** [awslabs/serverless-rules#177]
How can I stop this error being thrown when trying to define the deadletter queue?

```
Resources:

    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        KmsMasterKeyId: alias/aws/sqs

    MainQueue:
      Type: AWS::SQS::Queue
      Properties:
        KmsMasterKeyId: alias/aws/sqs
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
          maxReceiveCount: 3
```

I get the error... `SQS Queue DeadLetterQueue should have a RedrivePolicy property configured.`

**Comment by keironlowe-edriving** [comment]
Closing as I found the solution, you can attach metadata to a service to ignore specific errors, example below...

```
Resources:

    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Metadata:
        cfn-lint:
          config:
            ignore_checks:
              - ES6000
      Properties:
        KmsMasterKeyId: alias/aws/sqs
```
