### ISSUE TITLE
[cfn-lint] E0001: Lambda Timeout is invalid

### ISSUE THREAD

**Issue by stewartcampbell** [awslabs/serverless-rules#65]
I am linting a template generated by Troposphere the creates the following:

```
  Lambda:
    Properties:
      CodeUri:
        Bucket: !Sub 'xxxxx'
        Key: !Sub 'xxxxxxxxx'
      Events:
        SQSEvent:
          Properties:
            BatchSize: 10
            Queue: !GetAtt 'Queue.Arn'
          Type: SQS
      FunctionName: !Sub 'xxxxxxxxx'
      Handler: xxxxxxxxx
      MemorySize: 2048
      Runtime: java11
      Timeout: '60'
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt LambdaSecurityGroup.GroupId'
        SubnetIds:
          - !ImportValue 'AppSubnetA-Id-v2'
          - !ImportValue 'AppSubnetB-Id-v2'
          - !ImportValue 'AppSubnetC-Id-v2'
    Type: AWS::Serverless::Function
```

## Expected Behavior

Liniting to understand timeout is allowed.

If I remove the serverless rules from the cfn-lint extension in VSCode, linting is fine.

## Current Behavior

[cfn-lint] E0001: Error transforming template: Resource with id [AuditLambda] is invalid. Type of property 'Timeout' is invalid.

Note: this is shown for line 1 of the template, even though it is meant to be for the Lambda.

If I comment out `Timeout` I then get:

[cfn-lint] ES1006: Lambda function AuditLambda does not have a Timeout property
[cfn-lint] WS1000: Lambda function AuditLambda should have TracingConfig.Mode set to 'Active'.
[cfn-lint] WS1004: Lambda function AuditLambda does not have a corresponding log group with a Retention property

Note:This is correctly shown for the Lambda resource instead of line 1.

## Environment

WSL2 (Ubuntu 20.04.2 LTS) on Windows 10 
cfn-lint               0.51.0              
cfn-lint-serverless    0.1.9  
Python 3.8.5
