### ISSUE TITLE
Recurring SQS Redrive rule

### ISSUE THREAD

**Issue by sliedig** [awslabs/serverless-rules#79]
**What were you trying to accomplish?**
Validate SQS. Was presented a rule violation that said I needed a RedrivePolicy. Added the policy and DLQ, was presented with the same error against the DLQ.

## Expected Behavior
If a SQS queue is already configured as a DLQ for another SQS queue, don't run the rule on the DLQ.

## Current Behavior

I have this code

```
  SagaQueue:
    Type: AWS::SQS::Queue
```
you run the serverless rules and you rightly get

> ES6000 SQS Queue SagaQueue should have a RedrivePolicy property configured.
> template.yaml:314:3

So I add
  ```
SagaQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt SagaDeadLetterQueue.Arn
        maxReceiveCount: 5
  SagaDeadLetterQueue:
    Type: AWS::SQS::Queue
```
but now I get

> ES6000 SQS Queue SagaDeadLetterQueue should have a RedrivePolicy property configured.
> template.yaml:326:3

It will be a never ending story. 

## Possible Solution
Can this be fixed so it detects a DLQ but not run the redrive rule on that?

## Steps to Reproduce (for bugs)
Describes above

## Environment

* **Infrastructure as code technology used**:
* **(for `cfn-lint`) Python, cfn-lint, and cfn-lint-serverless versions**: cfn-lint 0.49.2 cfn-lint-serverless 0.2.0
* **(for `tflint`) Go, tflint versions**:
